### PR TITLE
Fix headline heirarchy in HISTORY.rst

### PR DESCRIPTION
**Pull request by salty-horse**
All of the headlines were on the same level.
In the docs, this caused the TOC to look like:

* History
* 0.1.2 (2015-06-23)
* 0.1.1 (2015-06-12)

### CODE REVIEW

**Comment by hugovk** [comment]
Note: The Python 3.2 build failure is unrelated to this docs change.

**Comment by salty-horse** [comment]
Thanks, @hugovk.

The build failure is a known issue, as the latest version of coverage doesn't support Python 3.2.
Consider sticking to coverage==3.7.1 for the Travis build.

Reference:
* https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using
* https://github.com/travis-ci/travis-ci/issues/4866

**Comment by hugovk** [comment]
@salty-horse Yep, see PR https://github.com/aparrish/pronouncingpy/pull/15 :)

**Comment by aparrish** [comment]
ooof good catch, thanks!

**Pull request merged**
