### PR TITLE
Some small refactorings

### PR DESCRIPTION
**Pull request by darius**
This was going to be the same change as John Wiseman submitted, but luckily I pulled updates before starting. The code looked so nice that I felt like messing with it further -- just refactoring for (I think) greater clarity. The first commit does speed it up a tiny bit.

Not included here: changing pronunciations to a dict mapping from word to list of phone strings. That change actually slowed the test run down.

### CODE REVIEW

**Comment by darius** [comment]
Ah, I'm afraid I missed the create-a-branch step in the contributing guidelines.

**Comment by aparrish** [comment]
sure, looks good

**Comment by aparrish** [comment]
for the record, I considered using a dict for the word-to-phones map, and I've implemented it that way for a bunch of CMU dict projects where the performance of word-to-phones specifically was important... with this library, though, I really wanted to emphasize the search/rhyme capabilities, both of which rely on a "full-table" regex search that doesn't benefit from the data being in a dict. I know the O(n) solution isn't ideal, but I figure since n is fixed (there are only so many words in the pronouncing dictionary, after all), the performance is never going to be all *that* bad.

**Comment by darius** [comment]
Yeah, I just figured the dict would be easy to try.

To speed up search, if it mattered enough, I guess I'd try putting all the phones into a suffix array or suffix tree? But that sounds like work.

**Pull request merged**
